import fs from "fs";
import path from "path";

export async function runExportSpec(projectRoot: string): Promise<void> {
  const statePath = path.join(projectRoot, ".knowledge", "state.json");
  if (!fs.existsSync(statePath)) {
    console.log("Knowledge base not initialized or state.json missing.");
    return;
  }

  try {
    const state = JSON.parse(fs.readFileSync(statePath, "utf-8"));
    const outputPath = path.join(projectRoot, "ARCH_SPEC.md");
    
    let content = "# Architectural Specification\n\nGenerated by Project Cortex.\n\n";

    content += "## Concepts\n\n";
    for (const [name, concept] of Object.entries(state.concepts || {})) {
      content += `### ${name}\n\n${(concept as any).description}\n\n`;
      if ((concept as any).failedApproaches?.length) {
        content += `#### Failed Approaches\n`;
        for (const fa of (concept as any).failedApproaches) {
          content += `- **${fa.summary}**: ${fa.reason}\n`;
        }
        content += "\n";
      }
    }

    content += "## Entities\n\n";
    for (const [name, entity] of Object.entries(state.entities || {})) {
      content += `### ${name}\n\n`;
      if ((entity as any).sourceFile) {
        content += `**Source**: \`${(entity as any).sourceFile}\`\n\n`;
      }
      content += `${(entity as any).description}\n\n`;
      
      const relationships = (entity as any).relationships || [];
      if (relationships.length > 0) {
        content += `#### Relationships\n`;
        for (const rel of relationships) {
          content += `- **${rel.kind}**: ${rel.target}\n`;
        }
        content += "\n";
      }

      const constraints = (entity as any).constraints;
      if (constraints) {
        content += `#### Constraints\n`;
        if (constraints.mustNotImport?.length) content += `- **Must Not Import:** ${constraints.mustNotImport.join(", ")}\n`;
        if (constraints.mustNotBeCalledBy?.length) content += `- **Must Not Be Called By:** ${constraints.mustNotBeCalledBy.join(", ")}\n`;
        if (constraints.contract) content += `- **Contract:** ${constraints.contract}\n`;
        content += "\n";
      }

      if ((entity as any).failedApproaches?.length) {
        content += `#### Failed Approaches\n`;
        for (const fa of (entity as any).failedApproaches) {
          content += `- **${fa.summary}**: ${fa.reason}\n`;
        }
        content += "\n";
      }
    }

    fs.writeFileSync(outputPath, content, "utf-8");
    console.log(`✅ Architectural Specification exported to: ${outputPath}`);
  } catch (err: any) {
    console.error("Failed to export specification:", err.message);
  }
}
